### PR TITLE
[R] Android.mk: Replace LOCAL_COPY_HEADERS

### PR DESCRIPTION
**Pull request by ix5**
LOCAL_COPY_HEADERS and BUILD_COPY_HEADERS headers have been deprecated in Q and will throw an error in R.

### CODE REVIEW

**Comment by ix5** [comment]
Related: 
- https://github.com/sonyxperiadev/camera/pull/123
- https://github.com/sonyxperiadev/device-sony-common/pull/707

**Comment by MarijnS95** [comment]
I would like this to be merged as it looks sane and is required to build R, but then we currently have nothing using `cash` to test this change with. That might actually be the perfect reason to merge it straight away. @jerpelea thoughts?

**Comment by ix5** [comment]
> but then we currently have nothing using cash to test this change with

Kagura is trucking on merrily on Q.

**Comment by MarijnS95** [comment]
@ix5 You are totally right, local was checked out on 8.1 branches where `cash` has not yet been picked (@haxk20 keep that on your TODO list :wink:). It is on 6.4 branches (obviously) which are compiling properly for you.

@jerpelea Merge this one too!

**Comment by stefanhh0** [comment]
I think this breaks android-10 legacy at least for Yoshino or did i do something wrong?

Anyway I just can revert this commit locally for me. And if Tone and Loire are not affected by this problem everything is fine, since Yoshino is officially not a legacy platform... else I'd suggest creating a `q-mr1-legacy` for this repository that does not contain this change.

```
[ 41% 49433/119534] target thumb C++: camera.msm8998_32 <= vendor/qcom/opensource/camera/QCamera2/HAL3/QCamera3HWI.cpp
FAILED: out/target/product/lilac/obj_arm/SHARED_LIBRARIES/camera.msm8998_intermediates/HAL3/QCamera3HWI.o
/bin/bash -c "PWD=/proc/self/cwd /usr/bin/ccache prebuilts/clang/host/linux-x86/clang-r353983c1/bin/clang++     -I vendor/qcom/opensource/camera/QCamera2/../mm-image-codec/qexif -I vendor/qcom/opensource/camera/QCamera2/../mm-image-codec/qomx_core -I vendor/qcom/opensource/camera/QCamera2/include -I vendor/qcom/opensource/camera/QCamera2/stack/common -I vendor/qcom/opensource/camera/QCamera2/stack/common/leak -I vendor/qcom/opensource/camera/QCamera2/stack/mm-camera-interface/inc -I vendor/qcom/opensource/camera/QCamera2/util -I vendor/qcom/opensource/camera/QCamera2/HAL3 -I hardware/qcom/media/msm8998/libstagefrighthw -I hardware/qcom/media/msm8998/mm-core/inc -I system/core/libion/kernel-headers -I system/core/libion/include -I vendor/qcom/opensource/camera/QCamera2/HAL -I out/target/product/lilac/obj/include/qcom/display -I hardware/qcom/display/sde/libqservice -I vendor/qcom/opensource/camera/QCamera2 -I out/target/product/lilac/obj_arm/SHARED_LIBRARIES/camera.msm8998_intermediates -I out/target/product/lilac/gen/SHARED_LIBRARIES/camera.msm8998_intermediates \$(cat out/target/product/lilac/obj_arm/SHARED_LIBRARIES/camera.msm8998_intermediates/import_includes)   -isystem out/target/product/lilac/obj/include -isystem kernel/sony/msm-4.9/common-headers/kernel-headers -c  -fomit-frame-pointer -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -faddrsig -Wimplicit-fallthrough -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-zero-as-null-pointer-constant -Wno-sign-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -nostdlibinc -msoft-float -march=armv8-a -mfloat-abi=softfp -mfpu=neon-fp-armv8 -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -D__ARM_FEATURE_LPAE=1 -target armv7a-linux-androideabi -Bprebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin  -Wsign-promo -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -Wno-gnu-include-next -fvisibility-inlines-hidden  -std=gnu++17 -mthumb -Os  -fno-rtti -Wall -Wextra -Werror -DFDLEAK_FLAG -DMEMLEAK_FLAG -DQCAMERA_HAL1_SUPPORT -DSYSTEM_HEADER_PREFIX=sys -DHAS_MULTIMEDIA_HINTS -D_ANDROID -DVANILLA_HAL -DUSE_DISPLAY_SERVICE -std=c++11 -std=gnu++1y -DDEFAULT_DENOISE_MODE_ON -DHAL3 -DQCAMERA_REDEFINE_LOG -DVENUS_PRESENT -DUBWC_PRESENT -DTARGET_MSM8996 -DUSE_CAMERA_METABUFFER_UTILS -DTARGET_HAS_CASH -D__ANDROID_API__=29 -D__ANDROID_VNDK__ -fPIC -D_USING_LIBCXX -DANDROID_STRICT   -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-tautological-unsigned-zero-compare -Wno-c++98-compat-extra-semi -Wno-return-std-move-in-c++11  -MD -MF out/target/product/lilac/obj_arm/SHARED_LIBRARIES/camera.msm8998_intermediates/HAL3/QCamera3HWI.d -o out/target/product/lilac/obj_arm/SHARED_LIBRARIES/camera.msm8998_intermediates/HAL3/QCamera3HWI.o vendor/qcom/opensource/camera/QCamera2/HAL3/QCamera3HWI.cpp"
vendor/qcom/opensource/camera/QCamera2/HAL3/QCamera3HWI.cpp:67:10: fatal error: 'cashsvr/cash_ext.h' file not found
#include <cashsvr/cash_ext.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
02:05:05 ninja failed with: exit status 1
```

**Pull request merged**
