### PR TITLE
[DNM] Properly fix node permissions and cash UID

### PR DESCRIPTION
**Pull request by Myself5**

### CODE REVIEW

**Comment by jerpelea** [comment]
cash ahould run with system permission!

**Comment by alviteri** [comment]
using user as root makes tof working at all in every case now ? @Myself5

**Comment by alviteri** [comment]
if yes your fix should be done there too https://github.com/sonyxperiadev/vendor-sony-oss-projection/blob/master/ucommsvr/vendor/etc/init/ucommsvr.rc

**Comment by Myself5** [comment]
@jerpelea please read the code... We move to system context right after setting proper permissions on the required sysfs. For that we require to start with root though.

That also means that ucommsvr can stay as system, as cashsvr will move to system later on, too.

All of that is also explained in the commit messages....

**Comment by kholk** [comment]
Guys, with this PR, CASH does indeed run as system...... Read the code......

**Pull request merged**
